name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Build & Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v2

      - name: Install Node 
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build   
        env:
          CI: false

      - name: Deplot to firebase
        uses: w9jds/firebase-action@master
        with: 
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}